#!/usr/bin/env -S cargo -Zscript
---
[package]
version = "0.0.0-alpha.2"
edition = "2024"

[dependencies]
serde_json = "1.0"
tap = "1.0"

[dependencies.compact_str]
features = ["serde"]
version = "0.9.0"

[dependencies.serde]
features = ["derive"]
version = "1.0"
---
/* ===========================================
Usage:
  1.
    rustup toolchain install nightly

  2.
    - UNIX Like (Non-embedded system):
      ./generate_json.rs
    - Other (e.g., Windows):
      cargo -Zscript generate_json.rs
=========================================== */
use std::{fs, io};

use compact_str::{CompactString as MiniStr, format_compact as fmt_compact};
use serde_json::{Value as JsonValue, json as new_json};
use tap::{Pipe, Tap};

const fn crate_name() -> &'static str {
  "cardbox-target"
}

// #[test]
fn main() -> io::Result<()> {
  let write_to_json = |s| fs::write("command.json", s);

  CommandJson::new()
    .pipe_ref(serde_json::to_string_pretty)?
    .pipe(write_to_json)
}

type CmdArr = Box<[MiniStr]>;
#[derive(Debug, Clone, Default, serde::Serialize)]
struct CommandJson {
  comments: JsonValue,

  build_linux_gnu: CmdArr,
  build_linux_musl: CmdArr,
  zig_build: CmdArr,

  // wasm32-wasip{1,2}
  wasi_targets: [MiniStr; 2],
  build_wasi_arrs: [CmdArr; 2],

  // Windows ["x86_64", "aarch64", "i686"]
  win_targets: [MiniStr; 3],
  build_win_arrs: [CmdArr; 3],

  // macOS ["aarch64", "x86_64"]
  mac_targets: [MiniStr; 2],
  build_mac_arrs: [CmdArr; 2],
}

fn do_not_edit_manually() -> JsonValue {
  let en = r#"This file is automatically generated by generate_json.rs; manual edits are not recommended."#;
  let zh = r#"此文件由 generate_json.rs 自动生成，请勿手动编辑！"#;
  let de = r#"Diese Datei wird automatisch von generate_json.rs generiert und sollte nicht manuell bearbeitet werden."#;

  new_json!({
    "English (en)": en,
    "中文 (zh)": zh,
    "Deutsch (de)": de,
  })
}

impl CommandJson {
  fn new() -> Self {
    let [build_linux_gnu, build_linux_musl, zig_build] =
      ["build_on_debian", "linux_musl", "zig"].map(|m| {
        let s = format!("cardbox_target::{m}::build_all_tested");
        generate_test_command_array(&s)
      });

    Self {
      comments: do_not_edit_manually(),
      build_linux_gnu,
      build_linux_musl,
      zig_build,

      wasi_targets: wasi_targets(),
      build_wasi_arrs: cargo_build_wasi(),

      win_targets: win_targets(),
      build_win_arrs: cargo_build_win(),

      mac_targets: mac_targets(),
      build_mac_arrs: cargo_build_mac(),
    }
  }
}

fn wasi_targets() -> [MiniStr; 2] {
  [1, 2].map(|i| fmt_compact!("wasm32-wasip{i}"))
}

fn win_targets() -> [MiniStr; 3] {
  ["x86_64", "aarch64", "i686"] //
    .map(|a| fmt_compact!("{a}-pc-windows-msvc"))
}

fn mac_targets() -> [MiniStr; 2] {
  ["aarch64", "x86_64"] //
    .map(|a| fmt_compact!("{a}-apple-darwin"))
}

fn cargo_build_mac() -> [CmdArr; 2] {
  mac_targets().map(|t| {
    cargo_build_base_vec(None)
      .tap_mut(|v| v.push(t))
      .into()
  })
}

fn cargo_build_win() -> [CmdArr; 3] {
  win_targets().map(|t| {
    "thin"
      .pipe(Some)
      .pipe(cargo_build_base_vec)
      .tap_mut(|v| v.push(t))
      .into()
  })
}

fn cargo_build_wasi() -> [CmdArr; 2] {
  wasi_targets().map(|t| {
    cargo_build_base_vec(None)
      .tap_mut(|v| {
        v.extend([t, "-Zbuild-std=std,panic_abort".into()]);
      })
      .into()
  })
}

fn cargo_build_base_vec(profile: Option<&str>) -> Vec<MiniStr> {
  [
    "cargo",
    "build",
    "--package",
    crate_name(),
    "--profile",
    profile.unwrap_or("fat"),
    "-v",
    "--target",
  ]
  .map(MiniStr::from)
  .to_vec()
}

fn generate_test_command_array(fn_name: &str) -> CmdArr {
  [
    "cargo",
    "test",
    "--package",
    "tests",
    "--test",
    "mod",
    "--all-features",
    "--",
    // "cardbox_target::build_on_debian::build_all_tested",
    fn_name,
    "--exact",
    "--nocapture",
    "--ignored",
  ]
  .into_iter()
  .map(MiniStr::from)
  .collect()
}
