name: Build Cardbox Target
env:
  # BUILDKIT_PROGRESS: plain
  _cargo_crate_name: cardbox-target
  _add_rs_src_toolchain: "%w[rustup component add rust-src --toolchain nightly].run_cmd"
  _using_get_command_json: "require_ci 'cardbox_target/get_command.rb'"
  _panic_abort_flags: "-Zunstable-options -Cpanic=immediate-abort"

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build_cardbox_target.yml
      - .github/_ci_/cardox_target/dockerfile
  workflow_dispatch:
    inputs:
      enabled_win:
        description: "Windows"
        type: boolean
      enabled_mac:
        description: "macOS"
        type: boolean
      enabled_wasi:
        description: "WebAssembly System Interface"
        type: boolean
      enabled_linux_gnu:
        description: "Linux Glibc"
        type: boolean
      enabled_bsd:
        description: "FreeBSD + OpenBSD + NetBSD + .."
        type: boolean
      enabled_linux_musl:
        type: boolean

defaults:
  run:
    shell: ruby --disable=gems cinnabar/ci.rb {0}

jobs:
  prepare:
    runs-on: ubuntu-slim
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0'

      - id: set_matrix
        shell: ruby -rjson {0}
        run: | #.#
          inputs = JSON.parse '${{ toJSON(inputs) }}'
          get_input = -> key {
            { enabled: inputs.fetch("enabled_#{key}", false) }
          }

          matrix_json =
            [
              { target: "wasi",       **get_input["wasi"] },
              { target: "linux-gnu",  **get_input["linux_gnu"] },
              { target: "linux-musl", **get_input["linux_musl"] },
              { target: "bsd",        **get_input["bsd"] },
              { target: "win", os: "windows-latest", **get_input["win"] },
              { target: "mac", os: "macos-latest", **get_input["mac"] },
            ]
            .select { |t| t[:enabled] }
            .map    { |h| h.delete_if { |k, _| k == :enabled } }
            .map   { |h| h.merge!(os: "ubuntu-latest") if h[:os].nil? }
            .compact
            .then { {include: _1} }
            .then { JSON.dump _1 }
          file = ENV['github_output'.upcase]
          value = "matrix=#{matrix_json}\n"
          File.write(file, value, mode: "a")
  build:
    needs:
      - prepare
    if: fromJSON(needs.prepare.outputs.matrix)['include'] || '' != ''
    strategy:
      # max-parallel: 2
      fail-fast: true
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v5
        with:
          # ~/.cargo/bin/
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{env._cargo_crate_name}}-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}

      - name: clone cinnabar
        uses: actions/checkout@v6
        with:
          repository: 2moe/cinnabar
          path: cinnabar
          ref: v0.0.9-alpha.0

      - name: build wasi
        if: matrix.target == 'wasi'
        env:
          RUSTFLAGS: ${{env._panic_abort_flags}}
        run: | #.#
          ${{env._add_rs_src_toolchain}}
          ${{env._using_get_command_json}}

          get_command("wasi_targets").each do |target|
            %w[rustup target add].push(target).run_cmd
          end
          get_command("build_wasi_arrs").each(&:run_cmd)

      - name: build linux gnu
        if: matrix.target == 'linux-gnu'
        run: | #.#
          ${{env._using_get_command_json}}
          get_command("build_linux_gnu").run_cmd

      - name: build linux musl
        if: matrix.target == 'linux-musl'
        run: | #.#
          ${{env._using_get_command_json}}
          get_command("build_linux_musl").run_cmd

      - name: zig build
        if: matrix.target == 'bsd'
        run: | #.#
          ${{env._using_get_command_json}}
          get_command("zig_build").run_cmd

      - name: build win bin
        if: matrix.target == 'win'
        run: | #.#
          ${{env._using_get_command_json}}

          get_command("win_targets").each do |target|
            %w[rustup target add].push(target).run_cmd
          end
          get_command("build_win_arrs").each(&:run_cmd)

      - name: build macOS bin
        if: matrix.target == 'mac'
        run: | #.#
          ${{env._using_get_command_json}}

          get_command("mac_targets").each do |target|
            %w[rustup target add].push(target).run_cmd
          end
          get_command("build_mac_arrs").each(&:run_cmd)
