name: Build Cardbox Target
env:
  # BUILDKIT_PROGRESS: plain
  CINNABAR_CI_LIBS: '["cardbox_target/get_command.rb"]'
  _cargo_crate_name: cardbox-target
  _add_rs_src_toolchain: "%w[rustup component add rust-src --toolchain nightly].run_cmd"
  _panic_abort_flags: "-Zunstable-options -Cpanic=immediate-abort"

on:
  workflow_dispatch:
    inputs:
      enabled_win:
        description: "Windows"
        type: boolean
      enabled_mac:
        description: "macOS"
        type: boolean
      enabled_wasi:
        description: "WebAssembly System Interface"
        type: boolean
      enabled_linux_gnu:
        description: "Linux Glibc"
        type: boolean
      enabled_bsd:
        description: "FreeBSD + OpenBSD + NetBSD + .."
        type: boolean
      enabled_linux_musl:
        type: boolean

defaults:
  run:
    shell: ruby --disable=gems cinnabar/ci.rb {0}

jobs:
  prepare:
    runs-on: ubuntu-slim
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
      invalid_matrix: ${{ steps.set_matrix.outputs.invalid_matrix }}
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0'

      - id: set_matrix
        shell: ruby -rjson {0}
        continue-on-error: true
        run: | #.#
          inputs = JSON.parse '${{ toJSON(inputs) }}'

          def runner_name(t) = {
            win: "windows",
            mac: "macos",
          }.fetch(t.to_sym, "ubuntu") + "-latest"

          matrix_arr = %w[wasi linux_gnu linux_musl bsd win mac].filter_map { |t|
            inputs["enabled_#{t}"] && { target: t, os: runner_name(t) }
          }

          file = ENV['github_output'.upcase]
          append_output = -> v { File.write(file, v + "\n", mode: "a") }
          [
            "invalid_matrix=#{matrix_arr.empty?}",
            { include: matrix_arr }
              .tap { pp _1 }
              .then { "matrix=#{JSON.dump _1}" }
          ].map(&append_output)
  build:
    needs:
      - prepare
    # String, not bool
    if: needs.prepare.outputs.invalid_matrix == 'false'
    strategy:
      # max-parallel: 2
      fail-fast: true
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v6

      - uses: actions/cache@v5
        with:
          # ~/.cargo/bin/
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/
            target/
          key: ${{env._cargo_crate_name}}-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}

      - name: clone cinnabar
        uses: actions/checkout@v6
        with:
          repository: 2moe/cinnabar
          path: cinnabar
          ref: v0.0.9-alpha.1

      - name: build wasi
        if: matrix.target == 'wasi'
        env:
          RUSTFLAGS: ${{env._panic_abort_flags}}
        run: | #.#
          ${{env._add_rs_src_toolchain}}

          rustup_add "wasi_targets"
          get_command("build_wasi_arrs").each(&:run_cmd)

      - name: build linux gnu
        if: matrix.target == 'linux_gnu'
        run: | #.#
          get_command("build_linux_gnu").run_cmd

      - name: build linux musl
        if: matrix.target == 'linux_musl'
        run: | #.#
          get_command("build_linux_musl").run_cmd

      - name: zig build
        if: matrix.target == 'bsd'
        run: | #.#
          get_command("zig_build").run_cmd

      - name: build win bin
        if: matrix.target == 'win'
        run: | #.#
          rustup_add "win_targets"
          get_command("build_win_arrs").each(&:run_cmd)

      - name: build macOS bin
        if: matrix.target == 'mac'
        run: | #.#
          rustup_add "mac_targets"
          get_command("build_mac_arrs").each(&:run_cmd)
